import { BLOCK_BASE_TYPES } from "../inquiry/types.js";

const BASE_TYPE_TAXONOMY = BLOCK_BASE_TYPES.join("|");

/**
 * Agent-facing description of research-related CLI commands.
 *
 * This command is meant to be consumed by LLM agents as a "canvas protocol"
 * for how to keep blocks on an Inquiry updated while working.
 */
export async function agentResearchCommands(): Promise<void> {
  const lines = [
    "notlabel — canvas protocol (same as `notlabel protocol`)",
    "",
    "Inquiries hold the central topic; **blocks** are the primary surface for research",
    "notes, sources, datasets, experiments, code, insights, corrections, agent findings—use **custom** only when nothing else fits.",
    "",
    "Core objects:",
    "- Inquiry: raw_input, refined_statement, type, status, preferred_language (default en), confidence, seed_topics, privacy.",
    "- Block (per inquiry):",
    "    kind (string label, required — e.g. reference, goal, question, idea)",
    `    base_type (required taxonomy): ${BASE_TYPE_TAXONOMY}`,
    "    content?, title?, data? (JSON), linked_block_ids? (other blocks in the same inquiry)",
    "    privacy, is_pinned, timestamps",
    "",
    "0) Discover public inquiries (optional, read-only; JWT only in CLI)",
    "   notlabel public list [--q \"keywords\"] [--page 0] [--limit 20] [--json]",
    "   notlabel public get <id> --json",
    "   notlabel public list-blocks <id> --json",
    "",
    "1) Create or select an Inquiry",
    "   - Create: notlabel inquiry create --raw-input \"<user text>\" [--type hypothesis|exploration|question] [--privacy private|public] [--preferred-language en] --json",
    "     • Capture: inquiry.id, inquiry.type, inquiry.status, inquiry.seed_topics (when available).",
    "   - Reuse:  notlabel inquiry list --status active --json  → pick one id.",
    "   - Inspect: notlabel inquiry get <id> --json",
    "",
    "2) Create blocks (append research to the inquiry)",
    "   Command:",
    "     notlabel inquiry research add-block <inquiry-id>",
    "       [--content \"<text>\"]   (optional for base_type source when --data has \"url\")",
    `       [--base-type ${BASE_TYPE_TAXONOMY}]   (default: note)`,
    "       [--kind <label>]                        (default: note)",
    "       [--title \"<short title>\"]",
    "       [--data '{\"key\":\"value\",...}']",
    "       [--linked-blocks id1,id2]",
    "       [--privacy private|public]",
    "       [--pinned true|false]",
    "       [--json]",
    "",
    "   Recommended conventions for kind (free-form) vs base_type:",
    "     - base_type source + kind reference  → data: { url, title, authors[], year? }",
    "     - base_type note + kind note         → observations",
    "     - base_type note + kind goal         → data: { priority?: \"high\"|\"medium\"|\"low\" }",
    "     - base_type insight + kind insight   → syntheses linking other blocks (use linked-blocks)",
    "",
    "   Recommended payload hygiene (agents):",
    "     - Pass --title on almost every add-block: short preview for lists/UI (easy to omit; don’t skip it).",
    "     - Keep --content as the main prose when you have narrative text; for source links, url in --data can stand alone.",
    "",
    "   Behavior:",
    "     - Each POST creates one block; the API returns the block JSON (not the full inquiry).",
    "     - Prefer many small blocks over one huge block.",
    "     - Use --json to capture id, kind, base_type, and content for machine-readable state.",
    "     - list-blocks JSON uses key \"items\" (not \"blocks\"). Single block: notlabel inquiry research get-block <block-id> [--json]",
    "",
    "2b) Update / delete / topic-scoped block",
    "   Get one block:",
    "     notlabel inquiry research get-block <block-id> [--json]",
    "   Patch fields (at least one flag):",
    "     notlabel inquiry research update-block <block-id> [--kind ...] [--base-type ...] [--title ...] [--content ...] [--data '{...}'] \\",
    "       [--linked-blocks id1,id2 --inquiry-id <inquiry-id> | --topic-id <topic-id>] [--privacy private|public] [--pinned true|false] [--json]",
    "   Soft-delete:",
    "     notlabel inquiry research delete-block <block-id> [--json]",
    "   Create on a Topic (POST /topics/:topicId/blocks; links must be blocks on same topic):",
    "     notlabel inquiry research add-block-on-topic <topic-id> [--content \"...\"] [--base-type ...] [--kind ...] [--data '{...}'] [--linked-blocks ...] [--pinned true|false] [--json]",
    "",
    "3) List blocks (read the canvas)",
    "   Command:",
    "     notlabel inquiry research list-blocks <inquiry-id>",
    "       [--base-type ...] [--kind ...] [--page <n>] [--limit <n>] [--pinned true|false]",
    "       [--sort updatedAt:desc|createdAt:desc]",
    "       [--json]",
    "",
    "   - Without --json: compact list with block id, base_type/kind, preview, and pagination.",
    "   - With --json: { items: Block[], pagination: { total, limit, page, has_next } }.",
    "   - Fast-path for grouped retrieval:",
    "       notlabel inquiry research list-blocks <id> --kind insight --page 0 --limit 20 --json",
    "     Use this to fetch only the newest insight group instead of all blocks.",
    "",
    "3b) Block annotations (comments / social)",
    "   List one block's thread:",
    "     notlabel inquiry research annotations list-block <inquiry-id> <block-id> [--json]",
    "   List whole inquiry (newest first):",
    "     notlabel inquiry research annotations list-inquiry <inquiry-id> [--json]",
    "   Add:",
    "     notlabel inquiry research annotations add <inquiry-id> <block-id> --body \"...\" [--parent <annotation-id>] [--json]",
    "   Update text (author or owner/maintainer):",
    "     notlabel inquiry research annotations update <inquiry-id> <block-id> <annotation-id> --body \"...\" [--json]",
    "   — Anyone who can read the inquiry may annotate; parent must be on the same block.",
    "",
    "3c) Inquiry highlight (preview + optional markdown report; PUT = owner only)",
    "   Read:",
    "     notlabel inquiry highlight get <inquiry-id> [--json]",
    "   Write (inline or --file JSON):",
    "     notlabel inquiry highlight set <inquiry-id> --title \"…\" --abstract \"…\" --key-findings '[\"…\"]' [--json]",
    "   body_md only (CLI GET + merge; highlight must already exist):",
    "     notlabel inquiry highlight set <inquiry-id> --body-md-file ./report.md [--json]",
    "   AI + activate:",
    "     notlabel inquiry highlight preview-activate <inquiry-id> [--json]",
    "",
    "3d) Tags (social metadata; stored in InquiryStats)",
    "   Add tags to inquiry:",
    "     notlabel social inquiries add-tags <inquiry-id> --tags \"machine learning,open science\"",
    "   Inspect current tags:",
    "     notlabel social inquiries stats <inquiry-id> [--json]",
    "   Explore tags:",
    "     notlabel social tags popular [--limit 20] [--json]",
    "     notlabel social tags search --q \"machine\" [--limit 10] [--json]",
    "",
    "4) Pull notification updates (new research only)",
    "   Notifications are valuable because they let an agent ask for deltas instead of",
    "   re-reading all blocks every cycle.",
    "   Commands:",
    "     notlabel notifications list --unread-only --json",
    "     notlabel notifications read <notification-id> --json",
    "     notlabel notifications read-by-source <source-token> --json",
    "",
    "   Recommended behavior:",
    "     - Poll unread notifications first to detect new updates quickly.",
    "     - If a notification is research-related, fetch the relevant inquiry blocks.",
    "     - Mark it as read after processing to avoid duplicate work.",
    "",
    "5) Typical agent loop",
    "   1. Start from an Inquiry (create or select).",
    "   2. Check unread notifications for fresh updates (delta ingest).",
    "   3. For each investigation step:",
    "        - choose base_type and kind,",
    "        - call: notlabel inquiry research add-block <id> --title \"...\" --content \"...\" --kind <k> --json",
    "   4. Periodically call:",
    "        - notlabel inquiry research list-blocks <id> --kind insight --page 0 --limit 20 --json",
    "      for focused, incremental reads of the latest insight blocks.",
    "",
    "6) When to activate the Inquiry",
    "   - Some backends default new inquiries to active; check status first with get/list.",
    "   - Activation command:",
    "       notlabel inquiry activate <id> --json",
    "   - Activation triggers orbit graph generation; you can poll:",
    "       GET /inquiries/<id>/orbit-graph",
    "     Blocks can be added before and after activation.",
    "",
    "Use blocks as a durable log of the investigation tied to the Inquiry.",
  ];

  console.log(lines.join("\n"));
}
