/**
 * Agent-facing description of research-related CLI commands.
 *
 * This command is meant to be consumed by LLM agents as a "canvas protocol"
 * for how to keep blocks on an Inquiry updated while working.
 */
export async function agentResearchCommands(): Promise<void> {
  const lines = [
    "notlabel — Agent Research Commands (canvas protocol)",
    "",
    "Inquiries hold the central topic; **blocks** are the primary surface for research",
    "notes, sources, experiments, code snippets, insights, and custom content.",
    "",
    "Core objects:",
    "- Inquiry: raw_input, refined_statement, type, status, confidence, seed_topics, privacy.",
    "- Block (per inquiry):",
    "    kind (string label, required — e.g. reference, goal, question, idea)",
    "    base_type (required taxonomy): note | experiment | source | code | insight | custom",
    "    content?, title?, data? (JSON), linked_block_ids? (other blocks in the same inquiry)",
    "    privacy, is_pinned, timestamps",
    "",
    "1) Create or select an Inquiry",
    "   - Create: notlabel inquiry create --raw-input \"<user text>\" [--type hypothesis|exploration|question] --json",
    "     • Capture: inquiry.id, inquiry.type, inquiry.status, inquiry.seed_topics (when available).",
    "   - Reuse:  notlabel inquiry list --status active --json  → pick one id.",
    "   - Inspect: notlabel inquiry get <id> --json",
    "",
    "2) Create blocks (append research to the inquiry)",
    "   Command:",
    "     notlabel inquiry research add-block <inquiry-id>",
    "       --content \"<text>\"",
    "       [--base-type note|experiment|source|code|insight|custom]   (default: note)",
    "       [--kind <label>]                        (default: note)",
    "       [--title \"<short title>\"]",
    "       [--data '{\"key\":\"value\",...}']",
    "       [--linked-blocks id1,id2]",
    "       [--privacy private|public]",
    "       [--json]",
    "",
    "   Recommended conventions for kind (free-form) vs base_type:",
    "     - base_type source + kind reference  → data: { url, title, authors[], year? }",
    "     - base_type note + kind note         → observations",
    "     - base_type note + kind goal         → data: { priority?: \"high\"|\"medium\"|\"low\" }",
    "     - base_type insight + kind insight   → syntheses linking other blocks (use linked-blocks)",
    "",
    "   Behavior:",
    "     - Each POST creates one block; the API returns the block JSON (not the full inquiry).",
    "     - Prefer many small blocks over one huge block.",
    "     - Use --json to capture id, kind, base_type, and content for machine-readable state.",
    "",
    "3) List blocks (read the canvas)",
    "   Command:",
    "     notlabel inquiry research list-blocks <inquiry-id>",
    "       [--base-type ...] [--kind ...] [--page <n>] [--limit <n>] [--pinned true|false]",
    "       [--sort updatedAt:desc|createdAt:desc]",
    "       [--json]",
    "",
    "   - Without --json: compact list with block id, base_type/kind, preview, and pagination.",
    "   - With --json: { items: Block[], pagination: { total, limit, page, has_next } }.",
    "   - Fast-path for grouped retrieval:",
    "       notlabel inquiry research list-blocks <id> --kind insight --page 0 --limit 20 --json",
    "     Use this to fetch only the newest insight group instead of all blocks.",
    "",
    "4) Pull notification updates (new research only)",
    "   Notifications are valuable because they let an agent ask for deltas instead of",
    "   re-reading all blocks every cycle.",
    "   Commands:",
    "     notlabel notifications list --unread-only --json",
    "     notlabel notifications read <notification-id> --json",
    "     notlabel notifications read-by-source <source-token> --json",
    "",
    "   Recommended behavior:",
    "     - Poll unread notifications first to detect new updates quickly.",
    "     - If a notification is research-related, fetch the relevant inquiry blocks.",
    "     - Mark it as read after processing to avoid duplicate work.",
    "",
    "5) Typical agent loop",
    "   1. Start from an Inquiry (create or select).",
    "   2. Check unread notifications for fresh updates (delta ingest).",
    "   3. For each investigation step:",
    "        - choose base_type and kind,",
    "        - call: notlabel inquiry research add-block <id> --content \"...\" --kind <k> --json",
    "   4. Periodically call:",
    "        - notlabel inquiry research list-blocks <id> --kind insight --page 0 --limit 20 --json",
    "      for focused, incremental reads of the latest insight blocks.",
    "",
    "6) When to activate the Inquiry",
    "   - Move to active when the user has explicitly confirmed the refined_statement.",
    "   - Activation command:",
    "       notlabel inquiry activate <id> --json",
    "   - Activation triggers orbit graph generation; you can poll:",
    "       GET /inquiries/<id>/orbit-graph",
    "     Blocks can be added before and after activation.",
    "",
    "Use blocks as a durable log of the investigation tied to the Inquiry.",
  ];

  console.log(lines.join("\n"));
}
